server:
  port: 9091

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      connection:
        CharSet: utf-8
        characterEncoding: utf-8
        useUnicode: true
