server:
  port: 9191

spring:
  application:
    name: auth
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      connection:
        CharSet: utf-8
        characterEncoding: utf-8
        useUnicode: true
logging:
  level:
    root: DEBUG
    org:
      hibernate:
        type: TRACE
      springframework:
        security: DEBUG
  pattern:
    level:
      org.hibernate.orm.jdbc.bind: TRACE