server:
  port: 9095
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rc_rent?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    auth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091
